[tool.poetry]
name = "empty-jupyter-bench"
version = "0"
description = ""
authors = ["Petr Tuma <petr.tuma@d3s.mff.cuni.cz>"]

[tool.poetry.dependencies]
python = "^3.10"
jupyterlab = "^4.1.3"
jupytext = "^1.16.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
